(()=>{
  const loader=document.getElementById("loader"),loaderBar=document.getElementById("loaderBar"),loaderScore=document.getElementById("loaderScore"),loaderStatus=document.getElementById("loaderStatus"),loaderPrompt=document.getElementById("loaderPrompt"),boost=document.getElementById("loaderBoost");
  let load=0,boosts=0,done=false;
  const paintLoader=()=>{const shown=Math.min(100,Math.round(load));loaderBar.style.width=`${shown}%`;loaderScore.textContent=`${String(shown).padStart(3,"0")}%`;loaderStatus.textContent=shown<38?"LOADING IDEAS":shown<72?"ALIGNING PIXELS":shown<100?"TESTING THE FLOW":"PORTFOLIO UNLOCKED"};
  const finishLoader=()=>{if(done)return;done=true;load=100;paintLoader();loaderPrompt.textContent=boosts?`Creative boost x${boosts} — nice work!`:"Creative engine ready";setTimeout(()=>{document.body.classList.remove("is-loading");loader.classList.add("is-complete");setTimeout(()=>loader.remove(),700)},280)};
  boost.addEventListener("click",()=>{boosts++;load=Math.min(100,load+12);boost.animate([{transform:"scale(1)"},{transform:"scale(.92)"},{transform:"scale(1)"}],{duration:220});paintLoader();if(load>=100)finishLoader()});
  const loadingTimer=setInterval(()=>{load+=load<70?3.5:2.2;paintLoader();if(load>=100){clearInterval(loadingTimer);finishLoader()}},65);
  document.getElementById("projectList").innerHTML=WORK.map(project=>`<article class="project-card reveal" style="--card-accent:${project.accent}"><span class="project-card__num">${project.num}</span><div class="project-card__copy"><p class="eyebrow">${project.scope}</p><h3>${project.title}</h3><p>${project.headline} ${project.outcome}</p><div class="project-card__tags">${project.tags.map(tag=>`<span>${tag}</span>`).join("")}</div></div><a class="project-card__media" href="${project.link}" aria-label="Read the ${project.title} case study"><img src="${project.coverImage}" alt="${project.title} project preview" loading="lazy">${project.isLive ? `<b class="cover-live-badge">Live</b>` : ""}<span>↗</span></a></article>`).join("");
  document.getElementById("experienceList").innerHTML=EXPERIENCE.map((item,index)=>`<article class="journey-item reveal"><small>${item.period}</small><div><h3>${item.role}</h3><p>${item.org}</p></div><span>0${index+1}</span></article>`).join("");
  const proof={complex:{name:"Start with SKYNET.",copy:"End-to-end ownership across research, information architecture, a scalable system, handoff and a shipped V2 product.",link:"pages/project.html?project=skynet"},research:{name:"Explore TrailFlix.",copy:"Mixed-method research translated into a focused movie discovery and ticket-booking flow.",link:"pages/project.html?project=trailflix"},speed:{name:"See Pristine Global.",copy:"A finance experience simplified, redesigned and approved within a focused four-week sprint.",link:"pages/project.html?project=pristine-global"},system:{name:"Open D-Learn.",copy:"A repeatable EdTech system built around microlearning, progress cues and adaptable components.",link:"pages/project.html?project=dlearn"}};
  const options=[...document.querySelectorAll(".proof-option")];options.forEach(option=>option.addEventListener("click",()=>{options.forEach(item=>item.classList.toggle("is-active",item===option));const result=proof[option.dataset.proof];document.getElementById("proofName").textContent=result.name;document.getElementById("proofCopy").textContent=result.copy;document.getElementById("proofLink").href=result.link}));
  document.querySelectorAll("[data-loop-carousel]").forEach(track=>{[...track.children].forEach(item=>{const clone=item.cloneNode(true);clone.setAttribute("aria-hidden","true");clone.querySelectorAll("img").forEach(image=>image.alt="");track.appendChild(clone)})});
  const menu=document.getElementById("menuButton"),header=document.getElementById("siteHeader"),menuLabel=menu.querySelector(".menu-button__label");menu.addEventListener("click",()=>{const open=header.classList.toggle("is-menu-open");menu.setAttribute("aria-expanded",String(open));menu.setAttribute("aria-label",open?"Cancel and close menu":"Open menu");menuLabel.textContent=open?"Cancel":"Menu"});header.querySelectorAll("nav a").forEach(link=>link.addEventListener("click",()=>{header.classList.remove("is-menu-open");menu.setAttribute("aria-expanded","false");menu.setAttribute("aria-label","Open menu");menuLabel.textContent="Menu"}));
  const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches,reveal=document.querySelectorAll(".reveal");if(reduced)reveal.forEach(item=>item.classList.add("is-visible"));else{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("is-visible");observer.unobserve(entry.target)}}),{threshold:.08});reveal.forEach(item=>observer.observe(item))}
  const backToTop=document.getElementById("backToTop");
  const updateBackToTop=()=>{
    const visible=scrollY>400;
    backToTop.classList.toggle("is-visible",visible);
    backToTop.inert=!visible;
  };
  addEventListener("scroll",updateBackToTop,{passive:true});
  updateBackToTop();
  const progress=document.getElementById("scrollProgress");addEventListener("scroll",()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${max?scrollY/max*100:0}%`},{passive:true});document.getElementById("year").textContent=new Date().getFullYear();
})();
