/*
  EDIT PROJECTS HERE.
  Add, remove or reorder section objects; the case-study template updates automatically.
  Supported section types: copy, bullets, stats, process, gallery, beforeAfter, quote.
*/
window.PROJECTS = {
  skynet: {
    slug: "skynet",
    externalUrl: "https://onelink.to/skynetapplication",
    isLive: true,
    number: "01",
    title: "SkyNet OTT",
    eyebrow: "Flagship case study · Shipped product",
    headline: "Making thousands of entertainment choices feel effortless.",
    summary: "A research-led redesign of Myanmar’s SkyNet streaming ecosystem—connecting live TV, movies, sports and subscriptions through one clearer experience.",
    year: "2025–26",
    role: "Lead Product Designer",
    duration: "End-to-end",
    team: "Product · Engineering · MarCom",
    tags: ["OTT", "Research", "Design system", "Mobile"],
    accent: "#d8ff58",
    impact: [{value:"Shipped",label:"V2 launched Dec 2025"},{value:"4",label:"personas shaped priorities"},{value:"5",label:"local competitors audited"}],
    cover: "../assets/images/skynet-cover.webp",
    sections: [
      { id: "context", label: "The setup", kicker: "01 / Context", title: "The product was growing. The experience needed to catch up.", type: "copy", body: ["SkyNet brings live TV, movies, series, sports and on-demand video to viewers across Myanmar. As its library expanded, users had more to watch—but more to navigate.", "The opportunity was not simply to add features. It was to make discovery, subscriptions and everyday viewing feel coherent for new and experienced users alike."] },
      { id: "challenge", label: "Challenge", kicker: "02 / Challenge", title: "Complex content, different viewing habits, one interface.", type: "bullets", intro: "Product evaluation and interviews exposed recurring friction:", items: ["Relevant content was difficult to discover", "Live TV and VOD felt like disconnected destinations", "Subscription choices lacked clarity", "Downloads, parental controls and sports schedules were hard to locate"], note: "How might we make a powerful streaming platform feel simple on the first visit?" },
      { id: "role", label: "My role", kicker: "03 / Ownership", title: "From ambiguous problem to shipped experience.", type: "stats", stats: [{value:"12",label:"core UX activities"},{value:"4",label:"primary personas"},{value:"5",label:"local competitors audited"},{value:"1",label:"scalable design system"}], body: "I owned research, product strategy, information architecture, flows, wireframes, UI, prototyping, system foundations and developer handoff—partnering with product, engineering and MarCom throughout delivery." },
      { id: "process", label: "Process", kicker: "04 / How it moved", title: "Evidence first. Pixels second.", type: "process", steps: [{title:"Listen",text:"Interview viewers and map the moments that broke trust."},{title:"Frame",text:"Audit navigation, content discovery and competitor patterns."},{title:"Make",text:"Prototype critical journeys and build reusable components."},{title:"Learn",text:"Test, refine, hand off and support post-launch UAT."}] },
      { id: "personas", label: "Personas", kicker: "05 / People", title: "Four viewers, four versions of ‘easy’.", type: "gallery", body: "The personas kept family sharing, sports urgency, discovery habits and digital confidence visible during decisions.", images: [
        {src:"../assets/research-images/Ms. Aye Thanda(persona) (1).webp",caption:"Aye Thandar"},
        {src:"../assets/research-images/Thura (Persona).webp",caption:"Thura"},
        {src:"../assets/research-images/Thuzar (persona).webp",caption:"Thuzar"},
        {src:"../assets/research-images/Mr. Sithu(persona).webp",caption:"Sithu"}
      ] },
      { id: "research", label: "Research", kicker: "06 / Signals", title: "The questions were simple. The answers changed the direction.", type: "gallery", body: "Research connected viewing behavior to product priorities: faster discovery, transparent subscription value and clearer live-event cues.", images: [{src:"../assets/research-images/Questions & Insights/Questions.webp",caption:"Questions worth asking"},{src:"../assets/research-images/Questions & Insights/Key Insights.webp",caption:"Signals that shaped the product"}] },
      { id: "competition", label: "Competition", kicker: "07 / Market", title: "Finding the whitespace in a crowded home screen.", type: "gallery", body: "A local-first audit exposed familiar category patterns—and room for SkyNet to lead with clearer grouping, stronger hierarchy and a premium but accessible tone.", images: [{src:"../assets/research-images/Competitor Analysis/Initial Analysis.webp",caption:"Initial audit"},{src:"../assets/research-images/Competitor Analysis/Competitor Feature Comparison.webp",caption:"Feature comparison"}] },
      { id: "system", label: "System", kicker: "08 / Design system", title: "The polished UI started as a very messy workspace.", type: "gallery", body: "Exploration became a system of tokens, states and reusable patterns designed to scale across content types and device sizes.", images: [{src:"../assets/research-images/The Messy Workspace/Screenshot 2026-08-16 123518.webp",caption:"Component exploration"},{src:"../assets/research-images/The Messy Workspace/Screenshot 2026-08-25 151342.webp",caption:"System in progress"},{src:"../assets/research-images/The Messy Workspace/Screenshot 2026-08-25 151855.webp",caption:"Assets and variants"},{src:"../assets/research-images/The Messy Workspace/Screenshot 2026-08-25 152504.webp",caption:"Handoff-ready library"}] },
      { id: "outcome", label: "Outcome", kicker: "09 / Result", title: "A clearer SkyNet, from first tap to next episode.", type: "beforeAfter", before:{src:"../assets/research-images/Before After Comparison/Before.webp",label:"Before"}, after:{src:"../assets/research-images/Before After Comparison/After.webp",label:"After"}, points:["Simplified primary navigation", "Stronger content hierarchy", "Reusable product-wide patterns", "More visible subscription and live-event cues"] },
      { id: "reflection", label: "Reflection", kicker: "10 / Looking back", title: "Clarity is a feature—and a team sport.", type: "quote", quote:"The strongest design decision was not a new screen. It was giving every content type a consistent logic users could learn once and reuse everywhere.", body:"This project strengthened how I connect research evidence, business constraints and system-level thinking. Next, I would instrument discovery and subscription funnels more deeply to validate the design with behavioral data." }
    ]
  },
  trailflix: {
    slug:"trailflix", number:"02", title:"TrailFlix", eyebrow:"Independent case study · Entertainment", headline:"From trailer overload to a confident movie choice.", summary:"A one-month mobile product case study connecting personalized trailer discovery, movie details, local showtimes and ticket booking in a single journey.", year:"2024", role:"UI/UX Designer", duration:"1 month", team:"Independent project", tags:["Mobile", "Mixed-method research", "0→1"], accent:"#ff7ac6", impact:[{value:"90%",label:"survey interest in a trailer-browsing app"},{value:"2",label:"personas synthesized"},{value:"1 mo",label:"research through prototype"}], cover:"../assets/legacy/trailflix/cover.png",
    sections:[
      {id:"context",label:"Overview",kicker:"01 / Product context",title:"Moviegoers had plenty to watch—and too many places to look.",type:"copy",body:["Trailers, ratings, cast information and cinema schedules were scattered across different channels. That abundance made it harder to distinguish new releases from older content and arrive at the cinema confident in a choice.","TrailFlix brings personalized recommendations, trailer previews, release information, local showtimes and ticket booking into one mobile experience."]},
      {id:"research",label:"Research",kicker:"02 / Evidence",title:"The demand was not for more trailers. It was for better decisions.",type:"stats",stats:[{value:"60%",label:"frequently watched trailers"},{value:"80%",label:"regularly visited cinemas"},{value:"90%",label:"likely to use a trailer app"},{value:"70%",label:"wanted local-theater discovery"}],body:"I combined online surveys, interviews, quantitative analysis and usability testing. The strongest pattern was a need to separate upcoming and current films clearly while keeping ratings, cast and cinema information close to the trailer."},
      {id:"challenge",label:"Key insights",kicker:"03 / Problem framing",title:"Four frictions shaped the product direction.",type:"bullets",intro:"Research moved the concept away from a generic video feed and toward decision support.",items:["Choice overload made trailers difficult to compare","Upcoming and older releases lacked clear separation","Ratings, cast and showtimes were fragmented","Users wanted a convenient mobile path to local cinemas"],note:"How might we help moviegoers move from curiosity to a confident booking without jumping between platforms?"},
      {id:"people",label:"Personas",kicker:"04 / People",title:"Two moviegoers, different motivations, one shared need for clarity.",type:"gallery",body:"The personas translated research into concrete priorities around time, confidence, accessibility and future viewing.",images:[{src:"../assets/legacy/trailflix/persona-a.webp",caption:"Persona — Koay Macgroves"},{src:"../assets/legacy/trailflix/persona-b.webp",caption:"Persona — Alex Turner"}]},
      {id:"structure",label:"Architecture",kicker:"05 / Product structure",title:"Connecting discovery, evaluation and booking as one journey.",type:"gallery",body:"The journey map and information architecture aligned the experience from first discovery through trailer evaluation, movie details, cinema selection and ticket purchase.",images:[{src:"../assets/legacy/trailflix/journey.webp",caption:"End-to-end journey map"},{src:"../assets/legacy/trailflix/information-architecture.webp",caption:"Information architecture"},{src:"../assets/legacy/trailflix/swot.webp",caption:"Competitor SWOT"}]},
      {id:"process",label:"Process",kicker:"06 / Process",title:"Research gave the interface a point of view.",type:"process",steps:[{title:"Research",text:"Surveyed and interviewed moviegoers about trailer and cinema habits."},{title:"Define",text:"Synthesized personas, pain points and the core decision journey."},{title:"Ideate",text:"Connected recommendations, details, theaters and booking."},{title:"Test",text:"Refined hierarchy and accessibility through usability feedback."}]},
      {id:"solution",label:"Solution",kicker:"07 / Interface",title:"A cinematic interface that keeps the decision moving.",type:"gallery",body:"The final concept separates viewing contexts clearly, foregrounds trailers and makes supporting information available without interrupting browsing.",images:[{src:"../assets/legacy/trailflix/ui-01.webp",caption:"Visual system and key screens"},{src:"../assets/legacy/trailflix/ui-02.webp",caption:"Core mobile experience"},{src:"../assets/legacy/trailflix/ui-03.webp",caption:"Accessibility and design rationale"}]},
      {id:"reflection",label:"Reflection",kicker:"08 / Reflection",title:"Discovery only works when people can act on it.",type:"quote",quote:"The product became stronger when I stopped treating trailers as content and started treating them as a decision-making tool.",body:"A future iteration would validate recommendation explanations, group planning and the real cinema-payment handoff with a broader audience."}
    ]
  },
  "pristine-global": {
    slug:"pristine-global", isLive:true, number:"03", title:"Pristine Global", eyebrow:"Client project · Shipped FinTech", headline:"Modernizing a loan journey without compromising trust.", summary:"A four-week Lean UX redesign of an outdated finance loan app—simplifying navigation, removing unnecessary application steps and making eligibility and review states easier to understand.", year:"2024", role:"UI/UX Designer", duration:"4 weeks", team:"Client · Product · Engineering", tags:["FinTech","Lean UX","Shipped mobile"], accent:"#ffb84d", impact:[{value:"4 wks",label:"fixed redesign timeline"},{value:"Approved",label:"first client presentation"},{value:"Live",label:"released product"}], cover:"../assets/legacy/pristine/cover.png", externalUrl:"https://onelink.to/4ra582",
    sections:[
      {id:"context",label:"Overview",kicker:"01 / Product context",title:"My first finance project started with a domain-learning sprint.",type:"copy",body:["The existing app combined an outdated visual language with a complex loan-application journey. Users had to interpret unfamiliar information and navigate unnecessary steps before they could apply.","Before redesigning, I learned the finance terminology, reviewed existing user feedback and aligned user needs with the client’s business requirements. The audience covered working adults aged 20–60."]},
      {id:"challenge",label:"Constraints",kicker:"02 / Constraints",title:"Four weeks to create clarity in an unfamiliar domain.",type:"bullets",intro:"The tight schedule made prioritization part of the design problem.",items:["Build finance-domain understanding quickly","Modernize a visibly outdated interface","Clarify pain points with limited research time","Balance application simplicity with business requirements"],note:"The final direction was approved immediately by the client and later released as the live product."},
      {id:"process",label:"Lean UX",kicker:"03 / Method",title:"Think. Make. Check. Repeat only where it mattered.",type:"process",steps:[{title:"Think",text:"Reviewed feedback, learned domain language and focused the research questions."},{title:"Make",text:"Simplified information architecture, loan categories and application steps."},{title:"Check",text:"Reviewed comprehension, hierarchy and trust cues with users and stakeholders."},{title:"Ship",text:"Prepared high-level flows and UI for implementation under privacy constraints."}]},
      {id:"transformation",label:"Before / after",kicker:"04 / Transformation",title:"The visual glow-up followed a structural one.",type:"beforeAfter",before:{src:"../assets/legacy/pristine/before-02.webp",label:"Before"},after:{src:"../assets/legacy/pristine/after-02.webp",label:"After"},points:["Clearer dashboard hierarchy","Categorized loan discovery","Reduced application ambiguity","More visible progress and confirmation"]},
      {id:"solution",label:"Major screens",kicker:"05 / Shipped experience",title:"Making loan eligibility and next steps visible before commitment.",type:"gallery",body:"Because of the organization’s privacy policy, this showcase focuses on high-level screens. The redesign clarifies available loans, required documents, profile settings and the application review stage.",images:[{src:"../assets/legacy/pristine/loan-menu.webp",caption:"Available loans and categories"},{src:"../assets/legacy/pristine/loan-detail.webp",caption:"Loan details and eligibility"},{src:"../assets/legacy/pristine/profile.webp",caption:"Profile and settings"},{src:"../assets/legacy/pristine/review-01.webp",caption:"Application review and confirmation"},{src:"../assets/legacy/pristine/review-02.webp",caption:"Loan progress and status states"}]},
      {id:"outcome",label:"Outcome",kicker:"06 / Outcome",title:"A clearer product, approved quickly and shipped live.",type:"stats",stats:[{value:"4",label:"week Lean UX sprint"},{value:"20–60",label:"target working-age audience"},{value:"1st",label:"presentation approval"},{value:"Live",label:"released on Google Play"}],body:"The new interface modernized the brand, simplified navigation and reduced unnecessary application steps while respecting the product’s privacy constraints."},
      {id:"reflection",label:"Reflection",kicker:"07 / Reflection",title:"Adaptability was the real deliverable.",type:"quote",quote:"Designing for finance taught me that clarity is not only a usability quality—it is a trust signal.",body:"The steep domain-learning curve and fixed timeline strengthened how I prioritize research, learn unfamiliar systems and make high-risk information easier to understand."}
    ]
  },
  dlearn: {
    slug:"dlearn", number:"04", title:"D-Learn", eyebrow:"Competition entry · EdTech", headline:"Turning 15 new words a day into a habit learners can sustain.", summary:"A two-week vocabulary-learning concept using contextual examples, quick quizzes, visual progress, badges, streaks and AI personalization to make daily microlearning feel achievable.", year:"2025", role:"UI/UX Designer", duration:"2 weeks", team:"Independent competition entry", tags:["EdTech","Gamification","AI concept"], accent:"#8ed8ff", impact:[{value:"15/day",label:"focused learning target"},{value:"2 wks",label:"validation to core UI"},{value:"1 loop",label:"learn, quiz and progress"}], cover:"../assets/legacy/dlearn/cover.png",
    sections:[
      {id:"context",label:"Overview",kicker:"01 / Product context",title:"Vocabulary tools often ask for motivation before they help create it.",type:"copy",body:["Learners described inconsistency, overwhelming content and repetitive practice as barriers to retention. Many tools lacked contextual understanding, visible progress and incentives that make returning feel worthwhile.","D-Learn was created as a competition entry. In two weeks, I ran quick validation and designed the core learning flow around one manageable promise: 15 new words each day."]},
      {id:"challenge",label:"Challenge",kicker:"02 / Problem framing",title:"Make a demanding habit feel small, repeatable and rewarding.",type:"bullets",intro:"Two questions kept the concept focused.",items:["How might we make 15 daily words feel manageable?","How might context and quizzes improve retention?","How might visible progress encourage consistency?","How might AI personalize practice without adding complexity?"],note:"The product strategy centered on daily microlearning rather than an endless library of vocabulary."},
      {id:"competition",label:"Competition",kicker:"03 / Market signals",title:"Learning from adjacent products without copying their game mechanics.",type:"gallery",body:"Duolingo and SAYA were reviewed for content strategy, visual identity, interaction patterns and motivation. The opportunity was to pair strong habit cues with more explicit contextual learning.",images:[{src:"../assets/legacy/dlearn/competitor-dlearn.webp",caption:"Duolingo — habit and gamification signals"},{src:"../assets/legacy/dlearn/competitor-saya.webp",caption:"SAYA — local learning context"}]},
      {id:"strategy",label:"Strategy",kicker:"04 / Product strategy",title:"A simple loop: learn in context, practise quickly, see progress.",type:"process",steps:[{title:"Explore",text:"Validated consistency and retention problems with learners."},{title:"Ideate",text:"Combined examples, bite-sized quizzes, badges and streaks."},{title:"Personalize",text:"Used goals, education level and performance to adapt practice."},{title:"Prototype",text:"Connected onboarding, daily lessons, quiz feedback and progress."}]},
      {id:"solution",label:"Core screens",kicker:"05 / Interface",title:"Personal enough to help, simple enough to repeat daily.",type:"gallery",body:"The experience asks only for information that improves recommendations, organizes daily lessons clearly, teaches vocabulary through examples and closes the loop with quick quizzes and progress feedback.",images:[{src:"../assets/legacy/dlearn/onboarding.webp",caption:"Goal-based onboarding"},{src:"../assets/legacy/dlearn/personalization.webp",caption:"Education-level personalization"},{src:"../assets/legacy/dlearn/home.webp",caption:"Daily learning dashboard"},{src:"../assets/legacy/dlearn/lesson.webp",caption:"Categorized lessons"},{src:"../assets/legacy/dlearn/progress.webp",caption:"Contextual learning and progress"},{src:"../assets/legacy/dlearn/quiz.webp",caption:"Pronunciation and quick quiz"}]},
      {id:"outcome",label:"Outcome",kicker:"06 / Outcome",title:"A focused concept that connects motivation to the learning method.",type:"stats",stats:[{value:"15",label:"new words per day"},{value:"2",label:"week design sprint"},{value:"3",label:"learn, quiz, progress loop"},{value:"AI",label:"performance-led personalization"}],body:"The concept was appreciated for its clarity and smart feature set. More importantly, every motivational element—badges, streaks and progress—was tied to a learning action rather than added as decoration."},
      {id:"reflection",label:"Reflection",kicker:"07 / Reflection",title:"Small details can make consistency feel possible.",type:"quote",quote:"The strongest gamification pattern was not a badge. It was showing learners that today’s goal was small enough to finish.",body:"A next iteration would test long-term retention, notification timing and whether AI personalization meaningfully improves practice rather than simply making it feel more advanced."}
    ]
  }
};
